config/routes.rb
Rails.application.routes.draw do
  resources :searches, only: %i[new create]
  root to: 'searches#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prompt.rb
class Prompt < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  mapping do
    indexes :text, type: :text
  end

  def self.search(query, options)
    params = {
      query: {
        match: {
          text: { query: query, fuzziness: "AUTO" }
        }
      },
      size: options[:size]
    }
    __elasticsearch__.search(params)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
  end

  def create
    @results = Prompt.search(params[:query], size: 25).records.to_a
    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prompt Search</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <h1>Prompt Search</h1>
    <br>
    <%= yield %>
  </body>
</html>

app/views/searches/_search_form.html.erb
<%= form_tag searches_path, method: :post do %>
  <%= text_field_tag :query, params[:query], autofocus: true %>
  <%= submit_tag 'Search' %>
<% end %>

app/views/searches/new.html.erb
<%= render 'search_form' %>

app/views/searches/show.html.erb
<%= render 'search_form' %>

<h2>Results</h2>

<% if @results.empty? %>
  <p>No results found</p>
<% else %>
  <ul>
    <% @results.each do |prompt| %>
      <li><%= prompt.text %></li>
    <% end %>
  </ul>
<% end %>